### PR TITLE
update the relation

### PR DESCRIPTION
**Pull request by veritem**
Updating the relations between user and Student entity

### CODE REVIEW

**Review by SauveJeanLuc — COMMENTED** [review]
I've noticed that u've commented the code to update user credentials while updating ones for Student,
However it's in much need due to the structure of CreateStudentDTo used for Updating.

E.g: While updating the student, one may pass a different FirstName to the previous one which is originally a property of the User Model.

**Review by SauveJeanLuc — COMMENTED** [review]
I've noticed that you removed User from the properties of Student,
Which I think might be a loss of a tone of important data.

E.g: Each Student has firstName, LastName, Gender, ... which are originally properties of the User Model.

**Review by SauveJeanLuc — COMMENTED** [review]
Another thing is that Student is being found as a property for User Model,
Which forces the case that every User must be a student.

I think this implementation might be false.

**Comment by veritem** [comment]
I'm not sure how you interpreted this the design

for commented code it just wanted to make spring run due to updated relations

**Comment by veritem** [comment]
The idea, is that the relation between a user and student is One-to-Many right?  

A user can be a student in year one, years two, and so on. you get the point 

I'm not sure what type of information will be lost, but this is a good design from my own perspective

**Review by SauveJeanLuc — APPROVED** [review]

**Pull request merged**
